### ISSUE TITLE
User Management

### ISSUE THREAD

**Issue by sharwinbobde** [fMeow/arangors#109]
Is anyone already working on the user management module of milestone `1.0.x` ?

If not, I'd like to pick it up.

**Comment by sharwinbobde** [comment]
@fMeow Now that it's merged, is it time to change the TODO and documentation?

```
(WIP) Milestone 1.0.x

Provides the API related to:

    (X) Graph Management
    (X) Index Management
    (X) User Management
```

**Comment by fMeow** [comment]
Sure
