### ISSUE TITLE
Document CRUD support?

### ISSUE THREAD

**Issue by 3699n** [fMeow/arangors#13]
Is any plan to implement the `Collection` `create_document`, `remove_document`, `update_document` methods in the near future? They are essential features for this crate. The api endpoints are rather simple to interact with, and I would be happy to implement these endpoints myself if you give me some guidance in regards to how to implement them with regards to your already existing crate architecture.

**Comment by fMeow** [comment]
Thank you. 

No plan on Document CURD method yet. This feature can be realized by AQL query and the latter one offers much more flexibility. You can filtered on a document's _id to get the exact document you want.

It's prioritized to implement useful but missing features. And document API are not considered `missing` thanks to AQL query.

**Comment by fMeow** [comment]
Now PR #19 is working on document supports. It should be released with v0.4.0.

**Comment by arn-the-long-beard** [comment]
Hey, we worked on it with @fMeow. Since I am new to rust, it takes me some time to code it. Please feel free to look at the PR and give your inputs :)
