### ISSUE TITLE
How to use tests

### ISSUE THREAD

**Issue by arn-the-long-beard** [fMeow/arangors#15]
Hey Mate ! How are you doing ? 
Since I have a lot of time and I decided to focus more on Rust for the next few days, I am working on the Apis that are not implemented. I know they are not priority but they are easier to reach because I am a baby at rust.

But before, I got some errors when I do `cargo test`

Here is the result 

> running 0 tests
> 
> test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out
> 
>      Running target/debug/deps/aql-61c500ad8a94bb5b
> 
> running 4 tests
> test common::test_setup ... ok
> test test_aql_str ... FAILED
> test test_aql ... FAILED
> test test_aql_bind_vars ... FAILED
> 
> failures:
> 
> ---- test_aql_str stdout ----
> thread 'test_aql_str' panicked at 'called `Result::unwrap()` on an `Err` value: Serde(Error("missing field `jwt`", line: 1, column: 75))', tests/aql.rs:1:1
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> 
> ---- test_aql stdout ----
> thread 'test_aql' panicked at 'called `Result::unwrap()` on an `Err` value: Serde(Error("missing field `jwt`", line: 1, column: 75))', tests/aql.rs:1:1
> 
> ---- test_aql_bind_vars stdout ----
> thread 'test_aql_bind_vars' panicked at 'called `Result::unwrap()` on an `Err` value: Serde(Error("missing field `jwt`", line: 1, column: 75))', tests/aql.rs:1:1
> 
> 
> failures:
>     test_aql
>     test_aql_bind_vars
>     test_aql_str
> 
> test result: FAILED. 1 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out
> 
> error: test failed, to rerun pass '--test aql'
> 

I get this error on both dev and master. I do not understand where the error is located because it says line 1 for each of them. It looks like not every test is used also.

What is your advice ?

Best regards,

Arn with a very long beard.

PS : I tried with  ./init_db.sh  file and then run tests but it still does not work.

**Comment by arn-the-long-beard** [comment]
Okay, I see I get 401 when I run the ./init_db.sh

**Comment by fMeow** [comment]
Yes, please create a PR and ask to merge into dev branch.

The `init_db.sh` and cargo test use a default credential if not specified. You may need to specify `ARANGO_ROOT_USER`, `ARANGO_ROOT_PASSWORD` , `ARANGO_USER` and `ARANGO_PASSWORD` as environment variable when runing cargo test. In bash, it's like:

```sh
$ ARANGO_ROOT_USER=root ARANGO_ROOT_PASSWORD=pwd ARANGO_USER=user ARANGO_PASSWORD=pwd cargo test
```

Since you have successfully run cargo test collection, the credential should be fine. Maybe caused by a faulty script in `examples` folder? Need more detail about the error when you run cargo test.

Thank you so much for your effort.

**Comment by arn-the-long-beard** [comment]
Hey, thank you for your explanation :)

I got the error just after I cloned the project or switch branch and then cargo test. There is nothing more I do. I will check the example folder as you suggest.

On my way to the PR !

**Comment by arn-the-long-beard** [comment]
Okay I found out why. The issue happened for here 
```

    let root_user = get_root_user();
    let root_password = get_root_password();
```

My credentials for root_user & root_password where actually wrong. My bad :)
