### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by arn-the-long-beard** [fMeow/arangors#22]
Hello, I was thinking that maybe we could have this file so we have quick instructions for people on how to help the project.

What do you think?

It can be good for beginners like me too.

**Comment by fMeow** [comment]
That's great. But what to contain in a `CONTRIBUTING.md` file?

**Comment by arn-the-long-beard** [comment]
Hoo yes, I should have give examples :)

1 - For example we could describe the way we write commit messages, depending of its content.

- `test: updated unit test` -> When we update code on unit test

- `doc: added doc for constructor` -> When we write documentation

- `fix: fixed deserialization bug due to error handling` -> When we fix a bug

- `feat: added collection::create_document` -> When we add a new feature

and more

2 - We could describe how we can write PR description maybe 

3 - We could describe how we write unit test


I am thinking about this kind of stuff, so we all know how we should write our commits and which best practice we should have. It can be obvious  and natural for some people but, beginners like me need it :P

And I think Rust is so awesome  ( and Arango also :D ), we are going to have more and more people joining and willing to help.

**Comment by arn-the-long-beard** [comment]
Ho yes I found this  https://gist.github.com/abravalheri/34aeb7b18d61392251a2

**Comment by fMeow** [comment]
Finally, now `arangors` has a contribution guide!

Thank you so much! :)
