### ISSUE TITLE
Database::create_edge_collection creates regular document collection

### ISSUE THREAD

**Issue by theduke** [fMeow/arangors#26]
Title says it all.

Unexpectedly, a regular document collection is created.

**Comment by fMeow** [comment]
Thanks to your PR(#27), it should be fixed now. I also add a minimal e2e test to ensure the `create_edge_collection` performs correctly.

**Comment by theduke** [comment]
Great. 

Due to the complexity of the API, it might be worthwile to investigate auto-generating base code from the official Swagger /OpenAPI specification, and then providing a nicer API on top.

I don't think the current OpenAPI code generators are of great quality though...

**Comment by arn-the-long-beard** [comment]
Hello, thank you for your work !!!

**Comment by TroyKomodo** [comment]
I think this is broken again.
@fMeow

**Comment by TroyKomodo** [comment]
Looking at the code it seems that the server expects an integer but the code serializes a string for the fields.

Perhaps using serde_repr rather than just aliasing the fields to 1 or 2.
