### ISSUE TITLE
Index Management

### ISSUE THREAD

**Issue by inzanez** [fMeow/arangors#32]
Hi

is there someone already working on index management?

**Comment by EpiFouloux** [comment]
https://www.arangodb.com/docs/stable/http/indexes-working-with.html#create-index
This feature should be implemented on the Collection module

**Comment by inzanez** [comment]
Yes, that's what I planned to do. But if someone already started on that, it would be quite a waste of time doing the same :-)

**Comment by EpiFouloux** [comment]
I investigated to se if I could simply add the methods to `Collection` but the endpoints are not relative to collections so a new `Index`struct and implementation must be done and I don't have time for that :/ But I'll gladly help you

**Comment by inzanez** [comment]
Yes, it will be a bit more than that I guess. I‘ll start a PR soon on that.

**Comment by fMeow** [comment]
I am currently working on graph and haven't investigate into Index implementation yet. 

Many thanks

**Comment by EpiFouloux** [comment]
@inzanez seeing you already made progress I'll wait for your pull request instead of trying to do a quick and dirty here

**Comment by inzanez** [comment]
> @inzanez seeing you already made progress I'll wait for your pull request instead of trying to do a quick and dirty here

Yes, I guess that makes sense. I should be finished with a first draft for review in the next few hours.

**Comment by Weasy666** [comment]
> 
> 
> I am currently working on graph and haven't investigate into Index implementation yet.
> 
> Many thanks

@fMeow is it currently possible to create a graph with arangors?

**Comment by EpiFouloux** [comment]
> is it currently possible to create a graph with arangors?

Are you talking about `Named Graphs` or simply edge traversal?

**Comment by Weasy666** [comment]
`Named Graphs`, but if that is not possible, then edge traversal would propably also do. That would then be purely possible in AQL, as far as i could see.

**Comment by EpiFouloux** [comment]
It is possible in AQL, you can also use a ODM/OGM

**Comment by Weasy666** [comment]
Do you maybe now how to create a `Named Graph` with AQL? I was not able to find a satisfying answer or example.

**Comment by EpiFouloux** [comment]
There is not, to create a named graph you need to use either:
- arangosh
- the web interface
- the HTTP API
`arangors` uses the HTTP API and I don't think the graph creation is yet implemented but you can fork the project and make a pull request if you know how to make that feature. I'm looking into it as well in order to improve my own tool [aragog](https://gitlab.com/qonfucius/aragog) based on `arangors` so I'll probably make a pull request in the future

**Comment by EpiFouloux** [comment]
@Weasy666 https://github.com/fMeow/arangors/pull/47 has basic graph management

**Comment by Weasy666** [comment]
Wow! That was fast 😅
