### ISSUE TITLE
Change log level of connection

### ISSUE THREAD

**Issue by Weasy666** [fMeow/arangors#34]
Could you maybe change the log level to debug? Otherwise, using arangors with r2d2_arangors in Rocket spams the console on starting the server, because the connection pool opens a lot of connections and on every connection the message gets printed.

https://github.com/fMeow/arangors/blob/cfa2ae99837747af74b40c86c7f9ab62bbf96193/src/connection/mod.rs#L219

**Comment by fMeow** [comment]
Sure, I wil change it.

**Comment by Weasy666** [comment]
Great! Thank you!
