### ISSUE TITLE
Add Named Graph Management

### ISSUE THREAD

**Issue by EpiFouloux** [fMeow/arangors#48]
Hello,

We don't have any option to create *Named Graphs* with `arangors` and I need the feature for my own crate.

Based on https://www.arangodb.com/docs/stable/http/gharial-management.html#drop-a-graph and the *Index management* Pull request by @inzanez I did this: https://github.com/fMeow/arangors/pull/47

I'm not sure if it's the way you want to do it but It works. The graphs are not editable, this can be a future pull request.

Thank you !

**Comment by fMeow** [comment]
Thank you so much for your great work!! I will have a look into this and merge ASAP.

**Comment by EpiFouloux** [comment]
I guess I need to write more tests but I'll wait until I'm sure the implementation works for you

**Comment by EpiFouloux** [comment]
@Weasy666 PR merged, you can use named graphs
