### ISSUE TITLE
Implement `Clone` on public structs

### ISSUE THREAD

**Issue by EpiFouloux** [fMeow/arangors#50]
Hello,

Since I'm working on a arango ORM/ODM and currently working on migrations and schema generation I use structs like `IndexSettings`, `Graph`, `EdgeDefinitions`, etc. But I sometimes need to clone them, I have workarounds using `serde` but I wonder if we could just make these structs derive `Clone` by default.

I can make a pull request for this but I don't know if you think it's useful or not.

**Comment by fMeow** [comment]
Why not?

The only case that I against implement `Clone` is something that can be updated, for instance `Document` with _id, _key and etc. In this case a `Clone` can result in an updated version and outdated version, which can cause confusion.

**Comment by EpiFouloux** [comment]
I put `Clone` on structs the user would create himself, line `Index` and `Graph`: https://github.com/fMeow/arangors/pull/51
