### ISSUE TITLE
reqwest + rustls

### ISSUE THREAD

**Issue by theduke** [fMeow/arangors#57]
reqwest has the `rustls-tls` feature that will use `rustls` instead of the native system openssl library.

Would be great to have an extra feature to toggle this.

**Comment by ManevilleF** [comment]
I think you can enable this in your project without `arangors` changing anything: [This Pull request](https://github.com/fMeow/arangors/pull/41)

**Comment by theduke** [comment]
No, that doesn't work, as explained in the PR.

**Comment by fMeow** [comment]
Sorry for the long delay.

I think found a solution, see [example](https://github.com/fMeow/arangors/tree/master/examples/reqwest_rustls) for detail.

**Comment by theduke** [comment]
I'm working on a generic http client not tied to any specific backend, which allows libraries like this to write against an independent client, and for the end user to pick the actual client via a separate crate.

If you're interested, I can ping you once I publish it.

**Comment by fMeow** [comment]
Thank you so much! @theduke 

I actually has already publish [one](https://crates.io/crates/uclient) with some minor modification on the `arangors::client` mod.

**Comment by fMeow** [comment]
With the v0.5.0, I have added two feature gate to enable rustls in reqwest.

I think this issue can be closed.

Thank you so much for your feedback!
