### ISSUE TITLE
Release: new version with transactions, analyzers and views?

### ISSUE THREAD

**Issue by mrtnzlml** [fMeow/arangors#59]
Hola! 👋 I saw that one month ago, this awesome commit landed: https://github.com/fMeow/arangors/commit/1be43ebef82a66ff1f203845b279a1ac8907da67

However, it doesn't seem to be released yet. 🤔 Would it be possible to release a new version with this change, please? Thank you very much for considering it! 🙂

**Comment by fMeow** [comment]
I thougth I had already release it. I am publishing it into v0.4.6 now

**Comment by mrtnzlml** [comment]
Great, I can close this now! I was starting to get worried that this project is abandoned.

@fMeow Would you please consider an upgrade to Tokio 1.0 as well? Arangors seems to be the last dependency blocking me from upgrading other ones. Thanks! 🙂
