### ISSUE TITLE
Example dependency using the blocking feature in README.md is wrong.

### ISSUE THREAD

**Issue by nahaharo** [fMeow/arangors#60]
README.md says that you need to select features as "blocking" to use synchronous feature.
But I think correct option for use synchronous is "reqwest_blocking".

Please change "features = ["blocking"]" to "features = ["reqwest_blocking"]".

Problem section
```toml
[dependencies]
## This one is async
arangors = { version = "0.4", default-features = false }
## This one is synchronous
arangors = { version = "0.4", features = ["blocking"], default-features = false }```

**Comment by fMeow** [comment]
This is not
