### ISSUE TITLE
Error Improvements

### ISSUE THREAD

**Issue by ManevilleF** [fMeow/arangors#67]
Hello,

In `arangors` there are two error types:
- `ArangoError` which map the ArangoDB HTTP responses whith code, error num and message
-  `ClientError` which is the global error enum, with a `ArangoError` variant and a few other variants which are irrelevant to the document operation responses.

I can make a Merge requests changes the error type of ArangoDB operations from `ClientError` to a `ArangoError`.

With the `From<>` implementation for `ClientError` this won't be breaking changes but it will at least allow more specific error handling.

**Comment by fMeow** [comment]
This is [a way to convert](https://github.com/fMeow/arangors/blob/2032c5c4724be7ce38866234e9caf54447baedcf/src/error.rs#L18) from `ArangoError` to `ClientError`. 

We can either explictly use `ClientError::from(arango_error)` or simple use a `?` to let rust do the conversion for us.
