### ISSUE TITLE
Improve error message when credentials for connection are wrong

### ISSUE THREAD

**Issue by arn-the-long-beard** [fMeow/arangors#69]
Hello guys ! It is a long time :smile: 

I am still continuing my journey on Rust :stuck_out_tongue: 

Well I saw today that if the credentials for connection are wrong we get this :

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("missing field `jwt`"

```

The error comes from there :

```rust

    #[maybe_async]
    async fn jwt_login<T: Into<String>>(
        arango_url: &Url,
        username: T,
        password: T,
    ) -> Result<String, ClientError> {
        #[derive(Deserialize)]
        struct JWT {
            pub jwt: String,
        }
        let url = arango_url.join("/_open/auth").unwrap();

        let mut map = HashMap::new();
        map.insert("username", username.into());
        map.insert("password", password.into());

        let jwt: JWT = serde_json::from_str(
            C::new(None)?
                .post(url, &serde_json::to_string(&map)?)
                .await?
                .body(),
        )
        .unwrap();
        Ok(jwt.jwt)
    }

```

Maybe we could improve the error message maybe and give an error like " Unauthorized" or something .

What do you think ?

I can make it if you want :wink:

**Comment by ManevilleF** [comment]
This doesn't seem to be a credentials error, this method can definetely be improved but it would seem that ArangoDb is returning something wrong.

Maybe you have an unsupported ArangoDB version?

**Comment by arn-the-long-beard** [comment]
Hey @ManevilleF , thank you for your answer. I am using `version: 3.6.11` .

My credentials were wrong actually and I tested it several times. That is the issue :smile:  to have an error message that does no match the right error that a user would expect . 

Instead of having an error like "401" wrong credentials, I get the error about jwt because arangodb did not return any jwt.

We should improve the method :wink:  to get the right error from arangodb instead of having the serialization error.

**Comment by ManevilleF** [comment]
I checked and I indeed manage to reproduce, it's strange that ArangoDB doesn't return a 401 using JWT when it does for Basic auth.

**Comment by ManevilleF** [comment]
```
Response { status: 401, version: HTTP/1.1, headers: {"x-content-type-options": "nosniff", "server": "ArangoDB", "connection": "Keep-Alive", "content-type": "application/json; charset=utf-8", "content-length": "75"}, body: "{\"code\":401,\"error\":true,\"errorMessage\":\"Wrong credentials\",\"errorNum\":401}" }
```
There seem to be a problem on the response check, usually `arangors` handles correctly the ArangoDB errors but in this case it seem to ignore that the status code is wrong.

**Comment by fMeow** [comment]
I find the problems. 
```rust
        let jwt: JWT = serde_json::from_str(
            C::new(None)?
                .post(url, &serde_json::to_string(&map)?)
                .await?
                .body(),
        )
```
We simply deserialzie the response from server without checking if the responses complain error. This is fixed in [this commit](https://github.com/fMeow/arangors/commit/f8c3303b8dfed894ab1939ac5eab8a4c3cbf2780).
