### ISSUE TITLE
Make fields on `InsertOption`, `UpdateOption`, etc public

### ISSUE THREAD

**Issue by ManevilleF** [fMeow/arangors#71]
enums like:
- `InsertOptions`
- `UpdateOptions`
- `ReplaceOptions`
- ...

all have their fields being private and we have to use the derived `TypedBuilder` for customization.

I have an issue with that, in some cases I want to leave a `None` value which is not possible in current implementation.

Example:
```rust
let builder = InsertOptions::builder();
if some_condition {
   builder.wait_for_sync(true);
}
builder.build()
```

So I have two proposals:
- Removing the `TypedBuilder` implementations and making a custom builder system
- Making the fields public allowing builder and custom 

Either way I can make a MR for this

**Comment by fMeow** [comment]
It is actually possible. The point is that TypedBuilder returns a new builder with a different type.

```rust
let builder = InsertOptions::builder();
let option = if some_condition {
   builder.wait_for_sync(true).build();
}
else{
   builder.build();
};
```

The pros of  TypedBuilder is that we can know if the code is wrong at compile time and achieve zero cost abstraction. But I do think it a little cubersome in this case that you have to use a single match for all the conditions you want.

**Comment by ManevilleF** [comment]
> It is actually possible. The point is that TypedBuilder returns a new builder with a different type.
> 
> ```rust
> let builder = InsertOptions::builder();
> let option = if some_condition {
>    builder.wait_for_sync(true).build()
> }
> else{
>    builder.build()
> };
> ```

I tried this and it doesn't work. The second option works but I put a lof of options and My code looks like this:

```rust
impl Into<UpdateOptions> for OperationOptions {
    fn into(self) -> UpdateOptions {
        // TODO: remove this builder pattern whe arangors resolves https://github.com/fMeow/arangors/issues/71
        if let Some(value) = self.wait_for_sync {
            UpdateOptions::builder()
                .keep_null(true)
                .wait_for_sync(value)
                .ignore_revs(self.ignore_revs)
                .return_new(true) 
                .return_old(false)
                .silent(false)
                .build()
        } else {
            UpdateOptions::builder()
                .keep_null(true)
                .ignore_revs(self.ignore_revs)
                .return_new(true)
                .return_old(false)
                .silent(false)
                .build()
        }
    }
}
```

**Comment by ManevilleF** [comment]
I tried again and it works

> It is actually possible. The point is that TypedBuilder returns a new builder with a different type.
> 
> ```rust
> let builder = InsertOptions::builder();
> let option = if some_condition {
>    builder.wait_for_sync(true).build()
> }
> else{
>    builder.build()
> };
> ```
> 
> The pros of TypedBuilder is that we can know if the code is wrong at compile time and achieve zero cost abstraction. But I do think it a little cubersome in this case that you have to use a single match for all the conditions you want.
> 
> We can also create a builder for each condition:
> 
> ```rust
> let option = if some_condition {
>    InsertOptions::builder().wait_for_sync(true).build()
> }
> else{
>    InsertOptions::builder().build()
> };
> ```
