### ISSUE TITLE
reqwest 0.11 breaks tokio dependencies

### ISSUE THREAD

**Issue by ManevilleF** [fMeow/arangors#72]
The `0.4.7` release bumped the `reqwest` dependency to 0.11 which depends on `tokio` 1.x instead of 0.2.x

`arangors` can no longer be used with `actix-web` until they release the v4 (still in beta) based on tokio 1.x.

I think this version bump should be mentioned in the Changelog as a breaking change or rollbacked

**Comment by fMeow** [comment]
Well, personally I don't regard a dependency bump a potential breaking API change. But it surely is a inconvinience. I think I can bump the current version to 0.5.0 and addtionally publish a 0.4.8 with all the same code except that reqwest remains at 0.10. 

But the future changes will not be added in the 0.4 world where reqwest is fixed at 0.10. Else it can be really tiresome to maintain. 

Sorry for the long wait and thank you so much for your feedback!

**Comment by ManevilleF** [comment]
Tokio dependencies are quite tricky and a big issue on many repositories.
Cargo can't resolve it as it causes a runtime crash.

It think your solution is good. The 0.4.7 should be yanked afterwards I think

**Comment by fMeow** [comment]
Now that the v0.4.8 is published, and I yanked the 0.4.7 to keep 0.4 consistently fixed at tokio v0.2.

**Comment by ManevilleF** [comment]
Thanks !
