### ISSUE TITLE
Is this project unmaintained?

### ISSUE THREAD

**Issue by mrtnzlml** [fMeow/arangors#77]
Hola @fMeow! 👋 I am following this project for some time already and I noticed that it takes a very long time to merge some PRs, dependencies are not being upgraded regularly and it generally seems like this project is no longer actively maintained.

What is the status? Do you need some extra help? It would be nice to clarify this situation and to know what is the future of this project.

Thank you very much! 😎

**Comment by ManevilleF** [comment]
The project is maintained and is very fast to add new ArangoDB http features when available. For example the transaction system or the implementation of the indexes and named graph management APIs were done really fast.

On the other hand, non urgent features are slower to be developed/merged.

I don't think @fMeow is abandoning the project nor is he stepping down as a maintainer

**Comment by fMeow** [comment]
This project is stil active.

Though I am busy on other project and as @ManevilleF said, features of low urgency is slow to be implemented. As for myself, the current implementation can almost meet my need, as long as I don't do management related task, like create a user, edit permission or so.

And contribution is always welcomed. Thank you all!

**Comment by mrtnzlml** [comment]
Thanks for the clarification! 😎
