### ISSUE TITLE
Are bind parameters passed on to HTTP API?

### ISSUE THREAD

**Issue by velvia** [fMeow/arangors#86]
Just curious, if we use parameter binding, is this passed through to the HTTP API, or is the final AQL constructed in the client side and passed through to HTTP?   This is sort of a security issue for us.

Thanks

**Comment by velvia** [comment]
I guess the answer is no, as I searched for the use of `bindVars` which is the HTTP API param for binding, and it is not in the repo.  Also the design of the API suggests that the AQL query is built as a string it seems and passed in.  So I guess we'd need to support a different API that allows for binding to happen via HTTP.

**Comment by d4h0** [comment]
> I guess the answer is no, as I searched for the use of bindVars which is the HTTP API param for binding, and it is not in the repo.

I'm pretty sure, this isn't correct.

Bind parameters are added via [AqlQuery](https://docs.rs/arangors/latest/arangors/aql/struct.AqlQuery.html)/[AqlQueryBuilder](https://docs.rs/arangors/latest/arangors/aql/struct.AqlQueryBuilder.html).

When you look at the source code of [AqlQuery](https://github.com/fMeow/arangors/blob/2c31587dd136a9818097cc8d44002e358bb8529c/src/aql.rs#L31), you'll see the following:

```rust
#[serde(rename_all = "camelCase")]
pub struct AqlQuery<'a> {
    // ...

    /// bind parameters to substitute in query string
    #[serde(skip_serializing_if = "HashMap::is_empty")]
    #[builder(default)]
    bind_vars: HashMap<&'a str, Value>,

    // ...
}
```

As you can see, the field for bind parameters is called `bind_vars`, but renamed to `bindVars` via serde (`#[serde(rename_all = "camelCase")]`).

**Comment by fMeow** [comment]
As @d4h0 pointed out, the `bind_vars` is serialize into HTTP API instead of SQL string. If you are concerned about something like AQL injection attach, you can feel safe.
