### ISSUE TITLE
add support for async/await using async-std

### ISSUE THREAD

**Issue by prabirshrestha** [fMeow/arangors#9]

**Comment by guoli-lyu** [comment]
I find to tedious to write almost the same code for both async and sync with only difference in the http request details. And I have wrote a crate named `maybe-async` to provide a possible non-trival way to toggle between sync and async with a feature gate. In this way, I can dissocaite the http request crate as well as arango types and API.

This is planning in the near future, maybe months later.

But, what do you mean by using async-std? AFAIK, the async-std crate provides only low level equivalent to rust std. And there is almost no upstream library implements web request by manual handling of raw socket bytes.

**Comment by fMeow** [comment]
In version 0.3, the `async` syntax is supported. If you want to stick with `async-std`, try to use `surf_async` feature and disable default features. The all connection to arangoDB are sended with `surf`.

Or you can implement a custom client, if you don't like surf and wanna use another HTTP client.

**Comment by prabirshrestha** [comment]
This is great. Thanks.
